---
title: "ltc_logistic_regression"
author: "NL"
date: "26/05/2020"
output: html_document
---


```{r cars}
library(skimr)

# Import the data
df_LTCdata_for_stats_FINAL <- read.csv("~/Desktop/capstone/df_LTCdata_for_stats_FINAL.csv", na.strings="", header=TRUE)
skim(df_LTCdata_for_stats_FINAL)
```



```{r cars}
# Add column with outbreak status
df_LTCdata_for_stats_FINAL$outbreak <- with(df_LTCdata_for_stats_FINAL, ifelse(is.na(Status), 'no', 'yes'))

# Update data types for some columns
df_LTCdata_for_stats_FINAL[, 'outbreak'] <- as.factor(df_LTCdata_for_stats_FINAL[, 'outbreak'])
df_LTCdata_for_stats_FINAL[, 'cleaned_name'] <- as.character(df_LTCdata_for_stats_FINAL[, 'cleaned_name'])

# Remove single LTC home (lennox hospital) with missing values for accreditation etc.
df <- df_LTCdata_for_stats_FINAL[!(is.na(df$accreditation)),]
skim(df)

# Create list of columns with that may not be needed for the analysis
location = c(1, 2, 8, 9, 19, 24, 25, 26, 27) # 2 represents LHIN
inspection_range = c(11, 14, 17)
inspection_count = c(10, 13, 16)
inspection_rank = c(12, 15, 18)
covid = c(20, 21, 22, 23)

# Create df using binned inspections data
binned = df[,-c(location, inspection_count, inspection_range, covid)]
skim(binned)

# # Combine categories of Municipal and Non-profit for home_type
# df$home.type[df$home.type == 'Municipal'] <- 'Non-Profit'
# df$home.type <- factor(df$home.type)

# Create df with inspections count data to be logtransformed
logtrans = df[,-c(location, inspection_range, inspection_rank, covid)]

```

## Assessing skewness
```{r cars}
# Check for R skewness in numeric predictors
library(e1071)
print(c(skewness(logtrans$number_beds), 
skewness(logtrans$total_inspections),
skewness(logtrans$X5y_inspections),
skewness(logtrans$X2y_inspections)))

qqnorm(logtrans$total_inspections); qqline(logtrans$total_inspections, col = 'red')
qqnorm(logtrans$X5y_inspections); qqline(logtrans$X5y_inspections, col = 'red')
qqnorm(logtrans$X2y_inspections); qqline(logtrans$X2y_inspections, col = 'red')
qqnorm(logtrans$number_beds); qqline(logtrans$number_beds, col = 'red')

# Visualize the effect of square root and log transformations the data
library(rcompanion)
# Log transformations are better for the inspections data
plotNormalHistogram(logtrans$total_inspections)
plotNormalHistogram(sqrt(logtrans$total_inspections))
plotNormalHistogram(log(logtrans$total_inspections))

plotNormalHistogram(logtrans$X5y_inspections)
plotNormalHistogram(sqrt(logtrans$X5y_inspections))
plotNormalHistogram(log(logtrans$X5y_inspections))

plotNormalHistogram(logtrans$X2y_inspections)
plotNormalHistogram(sqrt(logtrans$X2y_inspections))
plotNormalHistogram(log(logtrans$X2y_inspections))

# A square root transformation is better for number_beds
plotNormalHistogram(logtrans$number_beds)
plotNormalHistogram(sqrt(logtrans$number_beds))
plotNormalHistogram(log(logtrans$number_beds))

```

```{r }
# Transform the numeric variables in place
cols = c(6, 7, 8)
logtrans[cols] <- log(logtrans[cols])
logtrans[9] <- sqrt(logtrans[9])
skim(logtrans)

```

```{r }
# Assess the distribution of variables
xtabs(~outbreak + home.type, data=binned)
xtabs(~accreditation + home.type, data=binned)
xtabs(~short.stay + home.type, data=binned)
xtabs(~family.council + home.type, data=binned)
xtabs(~residents.council + home.type, data=binned)
xtabs(~residents.council + outbreak, data=binned)
xtabs(~accreditation + outbreak, data=binned)
xtabs(~short.stay + outbreak, data=binned)
xtabs(~family.council + outbreak, data=binned)
xtabs(~family.council + residents.council, data=binned)

```


## Fit the logistic regression
```{r }
# # Fit logistic regression against home type
# glm1 <- glm(outbreak~home.type, data = df2, family = 'binomial')
# summary(glm1)

# Fit logistic regression using binned inspection counts
binned_glm = glm(outbreak~.,family=binomial,data=binned)
summary(binned_glm)

# Fit logistic regression using binned inspection counts
logtrans_glm = glm(outbreak~.,family=binomial,data=logtrans)
summary(logtrans_glm)

```


```{r }
# Calculate McFadden's pseudo R2 
ll.null <- binned_glm$null.deviance/-2
ll.proposed <- binned_glm$deviance/-2
print((ll.null - ll.proposed)/ll.null)
1 - pchisq(2*(ll.proposed - ll.null), df = (length(binned_glm$coefficients)-1)) #pvalue

ll.null <- logtrans_glm$null.deviance/-2
ll.proposed <- logtrans_glm$deviance/-2
print((ll.null - ll.proposed)/ll.null)
1 - pchisq(2*(ll.proposed - ll.null), df = (length(logtrans_glm$coefficients)-1)) #pvalue


```


```{r }
# Create a new dataframe showing probability of outbreak and outbreak status
predicted.data <- data.frame(probability.of.outbreak=binned_glm$fitted.values, outbreak=binned$outbreak)

# Sort the above df
predicted.data <- predicted.data[order(predicted.data$probability.of.outbreak, decreasing=FALSE),]

# Add new col to df with rank
predicted.data$rank <- 1:nrow(predicted.data)

library(ggplot2)
library(cowplot)

ggplot(data = predicted.data, aes(x=rank, y=probability.of.outbreak)) +
  geom_point(aes(color=outbreak), alpha = 1, shape = 4, stroke = 2) +
  xlab("Index") + ylab("Predicted probability of an outbreak")
```


```{r cars}
# Create a new dataframe showing probability of outbreak and outbreak status
predicted.data <- data.frame(probability.of.outbreak=logtrans_glm$fitted.values, outbreak=logtrans$outbreak)

# Sort the above df
predicted.data <- predicted.data[order(predicted.data$probability.of.outbreak, decreasing=FALSE),]

# Add new col to df with rank
predicted.data$rank <- 1:nrow(predicted.data)

library(ggplot2)
library(cowplot)

ggplot(data = predicted.data, aes(x=rank, y=probability.of.outbreak)) +
  geom_point(aes(color=outbreak), alpha = 1, shape = 4, stroke = 2) +
  xlab("Index") + ylab("Predicted probability of an outbreak")
```


```{r }




```



```{r cars}

```


```{r cars}

```


```{r cars}

```

