---
title: "PHU stats"
author: "Sofia Bahmutsky"
date: "25/05/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(FactoMineR)
library(factoextra)

# load the data
data <- read.csv("/Users/Sofia/Desktop/data-599-capstone-statistics-canada/data/PMD-en/PHU_FINAL_prop.csv")

str(data)
percents <- c('copd.percent', 'asthma.percent', 'smokers.percent', 'hbp.percent')
data[,percents] <- lapply(data[,percents], function(x) as.numeric(gsub("[\\%,]", "", x))/100)

str(data)

names(data)[names(data) == "copd.percent"] <- "copd.prop"
names(data)[names(data) == "asthma.percent"] <- "asthma.prop"
names(data)[names(data) == "hbp.percent"] <- "hbp.prop"
names(data)[names(data) == "smokers.percent"] <- "smokers.prop"

# dropping unneeded cols
df <- subset(data, select = -c(X, DGUID, Reporting_PHU, fid, DBUID, PRUID_x, CSDUID_x, CMAUID_x, CMAPUID_x, HR_UID, DAUID, lon, lat, transit_na, suppressed))
  
# dropping some cols which may be not make sense in this analysis...(need to check with John i think)
df <- subset(df, select = -c(FATALprop, NOT.RESOLVEDprop, RESOLVEDprop))

           
head(df)
```

```{r}
# our reposonse variable is totalprop (the proportion of cases in a PHU) the location is the label fro each row. 

# the transit proximity column has missing values. For our purposes they can be changed to zeroes. missing values means that there is no data collected for transit proximity.

# textbook method- subset selection methods

library(glmnet)
x=model.matrix(TOTALprop~.-Location,df)[,-1] 
y <- df$TOTALprop
y <- as.vector(y)

# ridge regression method

# alpha = 0 is for ridge regression.

grid=10^seq(10,-2,length=100)
ridge.mod=glmnet(x,y,alpha=0,lambda=grid)

```


PCA
```{r}
df[is.na(df)] <- 0

# scaling
df_pca<- prcomp(df, scale. = TRUE)

#scree plot
plot(df_pca, type = "lines")

#show all component loadings
round(df_pca$rotation, 2)

#summary and biplot
summary(df_pca)
#biplot(df_pca)
```

 Based on Kaiser criterion, we would retain the first 5 components: *3.7672 1.7995 1.22849 1.06844 1.02332* 

```{r}
df_pca5 <- df_pca$x[,1:5]
df_pca5
```
