---
title: "Weekly Team Log - WEEK 1"
author: "Sofia Bahmutsky"
date: "04/05/2020"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Weekly Team Log - WEEK 1

### Week of April 27 to May 4

This week our group worked together and individually throughout the week. In general we worked on research and gathering resources and information to begin writing our proposal. 

1. Wednesday April 29 we had a virtual meeting with our capstone partners, Bruno St-Aubin and Marian Radulescu from Statistics Canada. The general idea of the project was introduced to us.

2. We worked together on the proposal, which we will send as a draft to our capstone partners on Tuesday May 5, so they will have time to review and provide us with feedback. We can make required edits for the final draft of the proposal after our next virtual meeting with our partners on May 6. 

3. We worked together to create presentation slides for Tuesday May 5 presentation to Dr. Scott Fazackerley and TA's. 

4. Individually, we each did personal research to get more background infomaiton about COVID-19 situation in Canada, especilly Ontario. 

