---
title: "Individual Work Log WEEK 3"
author: "Sofia Bahmutsky"
date: "13/05/2020"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Monday May 11

1. Zoom meeting with group 9:30am - 3pm

2. ODHF data cleaning and manipulation in Python, 2 hours

3. Reviewing scraping, trying to create a scraper for getting addresses to combine with ODHF data (4-5 hours)

## Tuesday May 12

I was driving from Calgary to Kelowna today...I did not have time to work this day. 

## Wednesday May 13

1. Group meeting 9am - 2pm (5 hours) 

2. Stats Canada zoom meeting 11am-11:30 (0.5 hour)

3. Going through all notebooks that everyone made. (2 hours)

4. Splitting up work for the rest of the week and next week (0.5 hours)

5. Download/install of qGIS. (1 hour)

6. Tutorial of qGIS ... QGIS is really hard to use. It always crashes or takes forever to do a small task. (5 hours)



## Thursday May 14

1. Loading data into qGIS (1 hour)

2. Filtering data from Canada DB's to show only Ontario (30 mins)

3. Combining Layers, DB's and PHU layer on top. (30 mins)

4. Trying to find a method to count the db's which do not fall easily into a particular PHU. Checking is there are DB's which overlap into 2 or more PHu's. (4 hours)

5. Fixing the github...it was broken becuase I tried to push files which were too large. (30 mins)
