---
title: "Individual Work Log WEEK 8 & 9"
author: "Sofia Bahmutsky"
date: "16/06/2020"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Monday June 15

1. Writing paper

2. Group meeting 9:30-3pm (6 hours)


## Tuesday June 16

1. Paper writing, research (8 hours)

2. Zoom meeting with Scott and TA's (1 hour)

3. Zoom meeting with KT and Ngan

4. Re-run all stats with new dataset... econ_kt.csv in PHU folder!

5. Working again on QGI, fixing up some polygon issues which were discovered.. (1 hour)


## Wednesday June 17

1. Group meeting, stats Canada meeting from 11-12.

2. Continue writing

3. Re-run the stats wth updated data.

## Thursday June 18

1. Writing a lot of the report

2. RE-running stats with the updated data and added health predictors

## Weekend

1. writing
2. making presentation slides
3. writing script



## Monday June 22

1. Group meeting 9:30-12 with Ngan and KT

2. Going over the results, talking about how to interpret everything

3. Wiriting script for presentation

4. made presentation slides

5. finished all my entire statistics analysis
6. finished the results section for the paper. 


## Tuesday June 23

1. Presentation!
2. watching all the other presentations...

