---
title: "Regression Analysis at PHU Level (includes recent health indicators)"
author: "Sofia Bahmutsky"
date: "17/06/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Data 
```{r}
library(dplyr)

# load the data
data <- read.csv("/Users/Sofia/Desktop/data-599-capstone-statistics-canada/PHU_analysis/data/econ.csv")

str(data)
data[is.na(data)] <- 0

# drop duplicate rows
#data <- data[-c(13, 28), ] 

# dropping unneeded cols, cleaning...
data <- data[-c(1, 3:39, 41:49, 61)]
data <- data[-c(26:35)]
#data

# calcualte the proportion of COVID-19 cases per PHU
#data$TOTAL_prop <- data$TOTAL/data$HRPOP
#data$FATAL_prop <- data$FATAL/data$HRPOP

# need to convert all percentages into proportion...
prop <- function(x) x/100
data <- data.frame(data[1:3], lapply(data[4:24], prop), data[25:28])
```


Keep only the predictors and response variables needed for the analysis
```{r}
final_cases <- subset(data, select = -c(Reporting_PHU, FATAL, TOTAL,  FATAL_prop, DBPOP))
final_fatalities <- subset(data, select = -c(Reporting_PHU, FATAL, TOTAL,TOTAL_prop,  DBPOP))
```

LASSO
```{r}
### LASSO
library(leaps)
library(corrplot)
library(glmnet)

y=na.omit(final_cases)
x=model.matrix(TOTAL_prop~.,final_cases)[,-1]
rownames(x)=c()
y=as.matrix(final_cases$TOTAL_prop)

lasso <- glmnet(x, y, alpha = 1)
plot(lasso, label = TRUE)
plot(lasso, xvar = "lambda", label = TRUE)

regfit.full=regsubsets(TOTAL_prop~.,final_cases, nvmax = 23)
reg.summary = summary(regfit.full)

reg.summary
reg.summary$rss
plot(reg.summary$rss ,xlab="Number of Variables ",ylab="RSS", type="l")

# plot suggests to keep ~8 predictors

set.seed(123) 
cv.lasso <- cv.glmnet(x, y, alpha = 1)
# Fit the final model on the training data
model <- glmnet(x, y, alpha = 1, lambda = cv.lasso$lambda.min)


plot(cv.lasso)
cv.lasso$lambda.min

coef(cv.lasso, cv.lasso$lambda.min)
# looks like the appropriate value for predictors is 4.
```

beta regression model...
```{r}
library(betareg)
beta_model <- betareg(TOTAL_prop~Arthritis..15.years.and.over.+Body.mass.index..adjusted.self.reported..adult..18.years.and.over...obese+Diabetes+Heavy.drinking+Physical.activity..150.minutes.per.week..adult..18.years.and.over.+Sense.of.belonging.to.local.community..somewhat.strong.or.very.strong +amenity,data = final_cases, link = "loglog")
summary(beta_model)

# checking the links.
sapply(c("logit", "probit", "cauchit","loglog", "cloglog"),
function(x) logLik(update(beta_model, link = x)))

# diagnostic plots.
plot(beta_model)
```


```{r}
library(dplyr)
library(ggplot2)
library(ggrepel)
library(ggiraphExtra)
library(plotly)



ggplot(final_cases, aes(x=Heavy.drinking, y=TOTAL_prop, col = amenity)) +
  theme_classic()+
  geom_point(alpha = 0.9, aes(colour=amenity), size=4) + 
 stat_smooth(method = "glm", family= "beta",formula = y ~ log(x), se = T, col = "gray", fill="lightgray") +
   xlab("Proportion of PHU which participates in heavy drinking regularly")+
  ylab("COVID-19 total cases (proportion)")+
  labs(col = "Amenity Richness")+
  ggtitle("COVID-19 Cases in Ontario PHU's")+
  scale_color_gradientn(colors = c("blue", "gold", "red")) +
 
ggrepel::geom_label_repel(data=data %>% filter(Heavy.drinking == 0.198), aes(label = Reporting_PHU, fill=factor(amenity)),label.size = 0.3, color = "black",  nudge_x = 0.055, nudge_y = 0.0015)+
  
geom_label( data=data %>% filter(TOTAL_prop> 0.004),aes(label=Reporting_PHU, fill = factor(amenity)), color = "black",label.size = 0.3, label.padding = unit(0.15, "lines"), nudge_x = 0.028, nudge_y = 0.00015)+ 
  
guides(fill=FALSE)+
scale_fill_manual(values = setNames(c("gold", "red"), levels(data$amenity)))
```



LASSO fatalities
```{r}
### LASSO
library(leaps)
library(corrplot)
library(glmnet)

y=na.omit(final_fatalities)
x=model.matrix(FATAL_prop~.,final_fatalities)[,-1]
rownames(x)=c()
y=as.matrix(final_fatalities$FATAL_prop)

lasso <- glmnet(x, y, alpha = 1)
plot(lasso, label = TRUE)
plot(lasso, xvar = "lambda", label = TRUE)

regfit.full=regsubsets(FATAL_prop~.,final_fatalities, nvmax = 23)
reg.summary = summary(regfit.full)

reg.summary
reg.summary$rss
plot(reg.summary$rss ,xlab="Number of Variables ",ylab="RSS", type="l")

# plot suggests to keep ~8 predictors

set.seed(123) 
cv.lasso <- cv.glmnet(x, y, alpha = 1)
# Fit the final model on the training data
model <- glmnet(x, y, alpha = 1, lambda = cv.lasso$lambda.min)


plot(cv.lasso)
cv.lasso$lambda.min

coef(cv.lasso, cv.lasso$lambda.min)
# looks like the appropriate value for predictors is around 4 or 5.



#beta regression model...

library(betareg)
final_fatalities$FATAL_prop <- final_fatalities$FATAL_prop+0.00001

beta_model2 <- betareg(FATAL_prop~Body.mass.index..adjusted.self.reported..adult..18.years.and.over...obese+Chronic.obstructive.pulmonary.disease..COPD..35.years.and.over.+Heavy.drinking+Sense.of.belonging.to.local.community..somewhat.strong.or.very.strong+amenity,data = final_fatalities, link = "loglog")
summary(beta_model2)

# checking the links.
sapply(c("logit", "probit", "cauchit","loglog", "cloglog"),
function(x) logLik(update(beta_model, link = x)))

# the highest Loglikelihood is when using the log-log link. Let us use that one.
# diagnostic plots.
plot(beta_model)

```

```{r}

ggplot(final_fatalities, aes(x=Sense.of.belonging.to.local.community..somewhat.strong.or.very.strong, y=FATAL_prop, col = amenity)) +
  theme_classic()+
  geom_point(alpha = 0.9, aes(colour=amenity), size=4) + 
  xlab("Proportion of PHU which reports a strong sense of belonging to their community")+
  ylab("COVID-19 fatalities (proportion)")+
  labs(col = "Amenity Richness")+
  ggtitle("COVID-19 Fatalities in Ontario PHU's")+
  scale_color_gradientn(colors = c("blue", "gold", "red")) +
stat_smooth(method = "glm",formula = y ~ log(x), se = T, col = "gray", fill="lightgray") +
#ggrepel::geom_label_repel(data=data %>% filter(hbp.prop < 0.16), aes(label = Location, fill=factor(amenity)),label.size = 0.3, color = "black",  nudge_x = 0.025, nudge_y = 0)+
  
#geom_label_repel( data=data %>% filter(FATAL_prop > 0.00035),aes(label=Reporting_PHU, fill = factor(amenity)), color = "black",label.size = 0.3, label.padding = unit(0.15, "lines"),nudge_x = 3, nudge_y = 0.5)+ 

 # geom_label_repel( data=data %>% filter(hbp.prop < 0.16 & hbp.prop > 0.14),aes(label=Location, fill = factor(amenity)), color = "black",label.size = 0.3, label.padding = unit(0.15, "lines"),nudge_x = 0.0275, nudge_y = 0.00002)+ 

  #geom_label_repel( data=data %>% filter(hbp.prop == 	0.179),aes(label=Location, fill = factor(amenity)), color = "black",label.size = 0.3, label.padding = unit(0.15, "lines"),nudge_x = -0.0275, nudge_y = 0.00002)+ 

guides(fill=FALSE)+
scale_fill_manual(values = setNames(c( "red"), levels(data$amenity)))
```
